group required, contract constructor, dependency
decus-io/decus-sol pull request #12
Opened 2021-03-24 09:19 UTC by fudorec

2021-03-24 22:00 UTC, bill-clippy requested changes

2021-03-24 22:00 UTC, bill-clippy commented on contracts/core/DeCusSystem.sol
> +    SignatureValidator signatureValidator;
Why no let `DeCusSystem` inherit `SignatureValidator`?

2021-03-24 22:00 UTC, bill-clippy commented on contracts/core/DeCusSystem.sol
> +        _setRoleAdmin(GROUP_ADMIN_ROLE, DEFAULT_ADMIN_ROLE);
No need to explictly set up `DEFAULT_ADMIN_ROLE`, as it is already the default admin for any new role. See [AccessControl.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/378531b70906c906461fa14e5631f0569b938257/contracts/access/AccessControl.sol#L65)

2021-03-24 22:00 UTC, bill-clippy commented on contracts/keeper/GroupRegistry.sol
>          _setRoleAdmin(GROUP_ADMIN_ROLE, DEFAULT_ADMIN_ROLE);
See comment above about `DEFAULT_ADMIN_ROLE`

2021-03-24 22:00 UTC, bill-clippy commented on contracts/keeper/KeeperRegistry.sol
>          _setRoleAdmin(KEEPER_ADMIN_ROLE, DEFAULT_ADMIN_ROLE);
See comment above about `DEFAULT_ADMIN_ROLE`

2021-03-24 22:00 UTC, bill-clippy commented on contracts/tokens/DeCus.sol
> +        _setRoleAdmin(MINTER_ROLE, DEFAULT_ADMIN_ROLE);
See comment above about `DEFAULT_ADMIN_ROLE`

2021-03-24 22:00 UTC, bill-clippy commented on contracts/tokens/EBTC.sol
> +        _setRoleAdmin(MINTER_ROLE, DEFAULT_ADMIN_ROLE);
See comment above about `DEFAULT_ADMIN_ROLE`

2021-03-25 01:35 UTC, fudorec commented on contracts/core/DeCusSystem.sol
> +    SignatureValidator signatureValidator;
Next PR

2021-03-25 03:10 UTC, merged